# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_0Vu4hxj31LG0qbsuBAFIAoTqzKVFMq
"""

import pandas as pd

# Creating a sample dataset
data = {
    'Product': ['Laptop', 'Phone', 'Tablet', 'Monitor', 'Keyboard'],
    'Price': [800, 500, 300, 200, 50],
    'Quantity': [10, 15, 8, 12, 25]
}

# Creating a DataFrame
df = pd.DataFrame(data)

# Calculating total sales for each product
df['Total Sales'] = df['Price'] * df['Quantity']

# Displaying the DataFrame
print("Sales Data:\n", df)

# Finding the product with the highest sales
max_sales_product = df.loc[df['Total Sales'].idxmax()]
print("\nProduct with the highest sales:\n", max_sales_product)

# Calculating total revenue
total_revenue = df['Total Sales'].sum()
print("\nTotal Revenue: $", total_revenue)