# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_bkyn3isV9VoOlusxeNt8bqTbmxfeyHa
"""

import pandas as pd

# Sample data as a dictionary (simulating a CSV read)
data = {
    'Department': ['HR', 'IT', 'HR', 'Finance', 'IT', 'Finance', 'HR', 'IT'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hank'],
    'Salary': [50000, 70000, 55000, 80000, 72000, 85000, 52000, 71000]
}

# Convert dictionary to DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print("Original DataFrame:")
print(df)

# Calculate average salary per department
avg_salary = df.groupby('Department')['Salary'].mean()

# Display the result
print("\nAverage Salary by Department:")
print(avg_salary)

# Find employees earning more than 60,000
high_earners = df[df['Salary'] > 60000]

# Display the result
print("\nEmployees earning more than 60,000:")
print(high_earners)